#To - Do - NumPy


Basic Vector and Matrix Operation with Numpy

In [1]:
# takes type and then the actual value to be printed finally then converts accordingly and returns it
def convertLength(x,type):
  if (type=="meters"):
    result=x*3.28
  elif(type=="feet"):
    result=x/3.28
  return result

# takes weight and the type and converts accordingly and returns it
def convertWeight(x,type):
  if (type=="kilograms"):
    result=x*2.20
  elif(type=="pounds"):
    result=x/2.20
  return result

# takes volume and the type and converts accordingly and returns it
def convertVolume(x,type):
  if (type=="liters"):
    result=x*3.78
  elif(type=="gallons"):
    result=x/3.78
  return result

In [3]:
conversion=input("Enter the type of conversion: length, weight, volume")
a=input("Enter the value to be converted: ")
try:
    a=int(a)
except:
    print("Invalid input")
type=input("Enter the type of value your entered: meters,feet,kilograms,pounds,liters,gallons")
match conversion:
  case "length":
    print(convertLength(a,type))
  case "weight":
    print(convertWeight(a,type))
  case "volume":
    print(convertVolume(a,type))

Enter the type of conversion: length, weight, volumelength
Enter the value to be converted: 5
Enter the type of value your entered: meters,feet,kilograms,pounds,liters,gallonsfeet
1.524390243902439


Qn.2

In [5]:
def sum(x):
  # takes a parameter list and provides the sum of the elements of list
  result=0
  for x in x:
    result+=x
  return result

def average(x):
  # takes a parameter list and returns the average of the elements
  result=0
  for x in x:
    sum+=x
  result=sum/len(x)
  return result

def maximum(x):
  # takes a parameter list and returns the maximum of the elements
  return max(x)

def minimum(x):
  # takes a parameter list and returns the maximum of the elements
  return min(x)

In [6]:
a=input("enter list separated by spaces")
try:
  list=[int(x) for x in a if x.isnumeric()]
except:
  print("Enter valid numbers")
operation=input("Enter operation: sum, average,maximum,minimum")
match operation:
  case "sum":
    print(sum(list))
  case "average":
    print(average(list))
  case "maximum":
    print(maximum(list))
  case "minimum":
    print(minimum(list))

enter list separated by spaces500
Enter operation: sum, average,maximum,minimumsum
5


Qn.3

In [7]:

def extract_every_other(lst):
  new_list=[x for index,x in enumerate(lst) if index%2==0]
  return new_list

print(extract_every_other([1,2,3,4,5,6]))

[1, 3, 5]


Qn.4

In [8]:

def get_sublist(lst,start,end):
  new_list=lst[start:end+1]
  return new_list

print(get_sublist([1,2,3,4,5,6],2,4))

[3, 4, 5]


Qn.5

In [9]:
def reverse_list(lst):
  new_list=lst[::-1]
  return new_list

print(reverse_list([1,2,3,4,5,6]))

[6, 5, 4, 3, 2, 1]


Qn.6

In [10]:
def remove_first_last(lst):
  new_list=lst[1:len(lst)-1]
  return new_list

print(remove_first_last([1,2,3,4,5]))

[2, 3, 4]


Qn.7

In [11]:
def get_first_n(lst,n):
  new_list=lst[:n]
  return new_list

print(get_first_n([1,2,3,4,5],3))

[1, 2, 3]


Qn.8

In [12]:
def get_last_n(lst,n):
  new_list=lst[len(lst)-n:]
  return new_list

print(get_last_n([1,2,3,4,5],2))

[4, 5]


Qn.9

In [13]:
def reverse_skip(lst):
  new_list=lst[::-1]
  new_list=new_list[1::2]
  return new_list

print(reverse_skip([1,2,3,4,5,6]))

[5, 3, 1]


Qn.10

In [14]:
def flatten(lst):
  new_list=[]
  for x in lst:
    for y in x:
      new_list.append(y)
  return new_list

print(flatten([[1,2,3],[4,5,6]]))

[1, 2, 3, 4, 5, 6]


Qn.11

In [15]:
def access_nested_element(lst,indices):
  for index in indices:
    lst=lst[index]
  return lst

print(access_nested_element([[1,2,3],[4,5,6],[7,8,9]],[1,2]))

6


Qn.12

In [36]:
from collections.abc import Sequence

def sum_nested(lst):
    total = 0
    for x in lst:
        if isinstance(x, Sequence) and not isinstance(x, (str, bytes)):  # Avoid treating strings as lists
            total += sum_nested(x)  # Recursively sum nested lists
        else:
            total += x  # Add integer values directly
    return total

# Test case
print(sum_nested([[1, 2], [3, [4, 5]], 6]))  # Output: 21




21


Qn.13

In [19]:


def remove_element(lst,elem):
  for x in lst:
    for y in x:
      if(y==elem):
        x.remove(y)
  return lst

print(remove_element([[1, 2], [3, 2], [4, 5]],2))

[[1], [3], [4, 5]]


Qn.14

In [40]:
def find_max(lst):
  max=0
  for x in lst:
    if(type(x)==list):
      for y in x:
        if(type(y)==list):
          for z in y:
            if(z>max):
              max=z
        else:
          if(y>max):
            max=y
    else:
      if(x>max):
        max=x
  return max

print(find_max([[1, 2], [3, [4, 5]], 6]))

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 13)

Qn.15

In [21]:

def count_occurences(lst,elem):
  count=0
  for x in lst:
    for y in x:
      if(y==elem):
        count+=1
  return count

print(count_occurences([[1, 2], [3, 2], [4, 2]],2))

3


Qn.16

In [22]:
def deep_flatten(lst):
  new_list=[]
  for x in lst:
    if(type(x)==list):
      for y in x:
        if(type(y)==list):
          for z in y:
            new_list.append(z)
        else:
          new_list.append(y)
    else:
      new_list.append(x)

  return new_list

print(deep_flatten([[1, 2], [3, [4, 5]], 6]))

TypeError: 'str' object is not callable

Qn.17

In [23]:

def average_nested(lst):
  avg=0
  sum=0
  length=0
  for x in lst:
    for y in x:
      sum+=y
      length+=1
  avg=sum/length
  return avg

print(average_nested([[1, 2], [3, 4], [5, 6]]))

3.5


Qn.18

In [24]:
import numpy as np
empty_arr=np.empty(2)
one_arr=np.ones((4,2))
full_arr=np.full((2,3),5)
zerolikearr=np.zeros_like(one_arr)
onelikearr=np.ones_like(one_arr)
lstarr=np.array([1,2,3,4])
print(empty_arr)
print(one_arr)
print(full_arr)
print(zerolikearr)
print(onelikearr)
print(lstarr)

[-5.73021895e-300  6.69145694e-310]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[5 5 5]
 [5 5 5]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[1 2 3 4]


Qn.19

In [25]:
range_arr=np.arange(10,49)
matrix=np.arange(0,9).reshape((3,3))
eye_matrix=np.eye(3)
rand=np.random.random((3,3))
mean=rand.mean()
rand1=np.random.random((10,10))
max=rand1.max()
min=rand1.min()
zeroarr=np.zeros((10,10))
zeroarr[6]=1
arr=[1,2,0,0,4,0]
reversearr=arr[::-1]
arrborder=np.zeros((3,3))
arrborder[0,:]=1
arrborder[:,0]=1
arrborder[:,-1]=1
arrborder[-1,:]=1
checkerboard=np.zeros((8,8))
checkerboard[1::2,::2]=1
checkerboard[::2,1::2]=1
print(range_arr)
print(matrix)
print(eye_matrix)
print(rand)
print(mean)
print(rand1)
print(max)
print(min)
print(zeroarr)
print(reversearr)
print(arrborder)
print(checkerboard)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.60159004 0.05002333 0.20628282]
 [0.59683611 0.96610958 0.28996237]
 [0.68172055 0.05105663 0.04721801]]
0.38786660303067183
[[0.75933278 0.30883751 0.51173949 0.37436534 0.87891984 0.96505725
  0.70546133 0.78086165 0.14240879 0.11839885]
 [0.17312641 0.66814797 0.40625833 0.09163419 0.95873345 0.91252137
  0.69970781 0.04410403 0.08944256 0.98773646]
 [0.02444506 0.80975451 0.90498371 0.89410576 0.94546798 0.8411343
  0.07476402 0.93541608 0.56488393 0.42749072]
 [0.16285681 0.2086353  0.92190161 0.33343622 0.01867834 0.45691287
  0.23393088 0.56993417 0.55139073 0.55002592]
 [0.99199902 0.42374686 0.25997395 0.5444455  0.00244096 0.50630883
  0.54409916 0.88294711 0.89124809 0.72207288]
 [0.34392532 0.19287015 0.37842817 0.04193816 0.170848   0.59545094
  0.97164224 0.76792025 0.23952207 0.0789081

Qn.20

In [26]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
sum=np.add(x,y)
sub=np.subtract(x,y)
multiply=np.multiply(x,y)
square=np.square(x)
vdotw=np.dot(v,w)
xdotv=np.dot(x,v)
xdoty=np.dot(x,y)
rowconcat=np.concatenate((x,y),axis=0)
columnconcat=np.concatenate((x,y),axis=1)
print(sum)
print(sub)
print(multiply)
print(square)
print(vdotw)
print(xdotv)
print(xdoty)
print(rowconcat)
print(columnconcat)

[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 5 12]
 [21 40]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 5 7 8]]


Qn.21

In [27]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
ainverse=np.linalg.inv(A)
eye=A@ainverse
AB=np.matmul(A,B)
BA=np.matmul(B,A)
At=np.transpose(A)
Bt=np.transpose(B)
ABt=np.transpose(AB)
BtAt=np.matmul(Bt,At)
print(eye)
print(AB)
print(BA)
print(ABt)
print(BtAt)


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
[[23 51]
 [13 29]]
[[23 51]
 [13 29]]
